Create 2023-03-10-NIH-Renewal
openforcefield/openforcefield.org pull request #447
Opened 2023-03-10 16:00 UTC by mrshirts

Posting NIH grant renewal

2023-03-10 19:52 UTC, j-wags requested changes
Looks like the PDF didn't end up getting added in any of the commits - Could you try adding, committing, and pushing it again?

2023-03-10 19:52 UTC, j-wags commented on content/community/news/science-updates/2023-03-10-NIH-Renewal.md
> +can move on to more of the other things that need to be done, and if it's closed; we'll it probably won't be that useful to people down the road anyway.
```suggestion
can move on to more of the other things that need to be done, and if it's closed; well it probably won't be that useful to people down the road anyway. 
```

2023-03-11 00:17 UTC, jchodera requested changes
I think we should rewrite this.

2023-03-11 00:17 UTC, jchodera commented on content/community/news/science-updates/2023-03-10-NIH-Renewal.md
> +current grant ends next year. In the interest, of open science, we are [posting the scientific parts of the proposal](../../../science/research/2023_03_06_Open_Force_Field_Initiative_NIH_R01.pdf).
There should be no commas between "In the interest, of open science, we are..."

2023-03-11 00:17 UTC, jchodera commented on content/community/news/science-updates/2023-03-10-NIH-Renewal.md
> +We've been very thankful to recieve significant funding from the NIH Institute of General Medical Sciences for OpenFF over the last three years
Change
```
We've been very thankful to recieve significant funding from the NIH Institute of General Medical Sciences for OpenFF over the last three years from the Focused Technology Research and Development program.
```
to
```
Over the past three years, Open Force Field Initiative activities focused on the development of general biomolecular force fields have been supported in part by [NIH grant R01 GM132386](https://reporter.nih.gov/search/kRW6qf5IVU2C_RfGNJmaIg/project-details/10166314) through the [NIGMS Focused Technology Research & Development R01 program](https://grants.nih.gov/grants/guide/pa-files/par-19-253.html).
```

2023-03-11 00:17 UTC, jchodera commented on content/community/news/science-updates/2023-03-10-NIH-Renewal.md
> +We feel that overall, as part of an open science project, it's better to be open about our plans rather than keep them secret.
We don't need to explain any of this. We just need to lead by example.

I'd cut this whole paragraph.

2023-03-15 23:46 UTC, jchodera commented
Superceded by #448

2023-03-15 23:46 UTC, closed without merging